### PR TITLE
Lab2 UX Design + Wireframe

### PR DESCRIPTION
**Pull request by AVPa1ly**

### CODE REVIEW

**Review by nastik1811 — CHANGES_REQUESTED** [review]
You overuse `<span>`. In most cases they could be replaced with headings (`<h1>`-`<h6>`) or `<p>`. Check out other comments in figma (I didn't comment every same mistake, but you should fix them everywhere, at least on desktop version)

**Comment by AVPa1ly** [comment]
Link to mockup. Only one issue left, I commented on it
https://www.figma.com/file/b5MnpqbGlkfYFiGIkzpJ2O/Mockup

**Review by nastik1811 — APPROVED** [review]
So, it's `10`. Great work 👍   
I hope the next stages will be at the same level :)

**Comment by AVPa1ly** [comment]
Thanks, I'll try to keep the quality level ;)

**Pull request merged**
